inherit: true

tools:
  external_code_coverage: true

checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - "_config/"
    - "cms/"
    - "docs/"
    - "framework/"
    - "images/"
    - "lang/"
    - "vendor/"
